### ISSUE TITLE
Galactic Map Generator - Manually create a list of suitable maps

### ISSUE THREAD

**Issue by MartinX3** [FAForever/gw-backend#19]
GW-Developer-Client

- [ ] **Allowed** Map-Developers get a list of their maps
- [ ] Each entry get a button to push the specific map into the galactic war map list
- [ ] In the new dialogue they can set parameters needed for the map list
- [ ] Then the map will be pushed into the list
- [ ] Parameters can later be adjusted (connected via map ID)

**Comment by MartinX3** [comment]
@Brutus5000 
is that issue okay?

**Comment by Brutus5000** [comment]
I would take a different approach.
a) We only want restricted users to push into the list.
b) We don't want that feature integrated into one of the FAF clients (it does not belong there).

The map vault is queryable from public (any client). We could add a selection feature into the gw developer client. You should choose and tag the maps in a gw client.

**Comment by MartinX3** [comment]
Updated.

**Comment by Brutus5000** [comment]
We can now solves this with random map generator.
