### ISSUE TITLE
Switch to the modern gradle 6.0

### ISSUE THREAD

**Issue by MartinX3** [FAForever/gw-backend#22]
- [ ] - Switch to Gradle 4.9
- [ ] - Update Dependencies to latest spring boot 1.5.x compatible version
- [ ] - Modify .travis.yml to work with gradle

**Comment by Brutus5000** [comment]
Migrating to gradle for the sake of using gradle is no improvement for me.
If it does bring nameable benefits in the current setup, we can talk about it.
If it doesn't I will reject any PRs going in this direction.

Especially in the Camunda environment Maven is still default and the best documented.

**Comment by MartinX3** [comment]
https://gradle.org/maven-vs-gradle/
Grade is better in many ways and its dependency management file is smaller.

You need a special dependency management camundo documentation like this:
https://github.com/camunda/camunda-bpm-spring-boot-starter/tree/2.2.0/examples/example-webapp-gradle
Or what do you mean?

**Comment by breucode** [comment]
I would like to work on this. Are you still objecting on using gradle @Brutus5000 ?

**Comment by Brutus5000** [comment]
@breucode Go for it 👍
